#%RAML 1.0 DataType

description: An user's basic information.
properties:
  userId: 
    type: integer
    description: The user's ID
  username: 
    type: string
    description: The user's name
  playername: 
    type: string
    description: The user's ingame name