#%RAML 1.0 DataType

description: An user's session network information
properties:
  ipAddress:
    type: string
    description: The user's IP address
  clientPort:
    type: integer
    description: The user's client port
    minimum: 0
    maximum: 65535
  serverPort:
    type: integer
    description: The user's server port
    minimum: 0
    maximum: 65535
  tvPort:
    type: integer
    description: The user's SourceTV port
    minimum: 0
    maximum: 65535
