#%RAML 1.0
title: CSO2 User Service
description: The user's service API, meant to be used internally. Should an authentication method be used?
version: 0.0.1

types:
  # shared data types
  BaseUser:
    description: An user's basic information.
    properties:
      userId: 
        type: integer
        description: The user's ID
      username: 
        type: string
        description: The user's name
      playername: 
        type: string
        description: The user's ingame name
  User:
    type: BaseUser
    description: An user's full information.
    properties:      
      level:
        type: integer
        description: The user's level
        minimum: 1
        maximum: 255
      currentXp:
        type: integer
        description: The user's current experience
      maxXp:
        type: integer
        description: The user's level maximum experience
      wins:
        type: integer
        description: The user's match wins
      losses:
        type: integer
        description: The user's match losses
      kills:
        type: integer
        description: The user's kills
      deaths:
        type: integer
        description: The user's deaths
      assists:
        type: integer
        description: The user's assists
  UserInventoryItem:
    description: An user's inventory item.
    properties:
      itemId:
        type: integer
        description: The item's ID number
      ammount:
        type: integer
        description: The ammount of an user's item
        minimum: 1
  UserCosmetics:
    description: An user's equipped cosmetics.
    properties:
      ctItem:
        type: integer
        description: The loadout's CT character item ID
      terItem:
        type: integer
        description: The loadout's Terrorist character item ID
      headItem:
        type: integer
        description: The loadout's head wearable item ID
      gloveItem:
        type: integer
        description: The loadout's glove wearable item ID
      backItem:
        type: integer
        description: The loadout's backpack wearable item ID
      stepsItem:
        type: integer
        description: The loadout's footsteps item ID
      cardItem:
        type: integer
        description: The loadout's card item ID
      sprayItem:
        type: integer
        description: The loadout's spray item ID
  UserLoadout:
    description: An user's inventory loadout.
    properties: 
      loadoutNum: 
        type: integer
        description: The user's loadout number
        minimum: 0
        maximum: 2
      primary: 
        type: integer
        description: The user's loadout primary weapon item ID
      secondary: 
        type: integer
        description: The user's loadout secondary weapon item ID
      melee: 
        type: integer
        description: The user's loadout melee weapon item ID
      hegrenade: 
        type: integer
        description: The user's loadout explosive grenade item ID
      flash: 
        type: integer
        description: The user's loadout flashbang item ID
      smoke: 
        type: integer
        description: The user's loadout smoke grenade item ID
  UserBuySubMenu:
    description: An user's inventory sub buy menu details.
    properties:
      index:
        type: number 
      weapons:
        type: integer[]
        minItems: 0
        maxItems: 10
  UserBuyMenu:
    description: An user's inventory buy menu details.
    properties: 
      pistols: 
        type: UserBuySubMenu
        description: The user's pistols buy sub menu
      shotguns: 
        type: UserBuySubMenu
        description: The user's shotguns buy sub menu
      smgs: 
        type: UserBuySubMenu
        description: The user's SMGs buy sub menu
      rifles: 
        type: UserBuySubMenu
        description: The user's rifles buy sub menu
      snipers: 
        type: UserBuySubMenu
        description: The user's snipers buy sub menu
      machineguns: 
        type: UserBuySubMenu
        description: The user's machine guns buy sub menu
      melees: 
        type: UserBuySubMenu
        description: The user's melees buy sub menu
      equipment: 
        type: UserBuySubMenu
        description: The user's equipment buy sub menu

  # requests/responses  
  SignupRequest:
    description: A request to create a new user.
    properties:
      username: 
        type: string
        description: The target user's name
      playername: 
        type: string
        description: The target user's ingame name
      password:
        type: string
        description: The target user's secret password
  LoginRequest:
    description: A request to login an user.
    properties:
      username: 
        type: string
        description: The target user's name
      password:
        type: string
        description: The target user's secret password

/users:
  description: The user's API base
  get:           
    responses:
      200:
        description: The user's information.
        body:
          application/json:
            type: BaseUser[]
            description: Every users' basic information.
            example:
              - userId: 123
                username: "gamer"
                playername: "VeryGoodGamer"
              - userId: 456
                username: "ilovecso2"     
                playername: "ReallyLikeCSO2"    
      400:
        description: The request is malformed.
  /{userId}:
    uriParameters:
      userId:
        type: integer
        description: The user's ID number.  
    get:
      description: Request to get an user's information.      
      responses:
        200:
          description: The user's information.
          body:
            application/json:
              type: User
              description: The requested user's information.
              example:
                userId: 123
                username: "gamer"
                playername: "VeryGoodGamer"
                level: 25
                currentXp: 32100
                maxXp: 45000
                wins: 230
                losses: 215
                kills: 1521
                deaths: 1324
                assists: 540                
        400:
          description: The request is malformed.
        404:
          description: The user does not exist.
    /inventory:
      get: 
        description: Request an user's inventory items           
        responses:
          200:
            description: The user's inventory items
            body:
              application/json:
                type: UserInventoryItem[]
                description: The requested user's inventory items.
                example:
                  - itemId: 100
                    ammount: 3
                  - itemId: 200
                    ammount: 1
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
      post:
        description: Add item to an user's inventory
        body:
          application/json:   
            type: UserInventoryItem
            description: The new item to add to an user's inventory.
            example:
              itemId: 10092
              ammount: 1          
        responses:
          200:
            description: The item was added successfully
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
      delete: 
        description: Remove an item in an user's inventory
        body:
          application/json:   
            type: UserInventoryItem
            description: The item to delete from an user's inventory.
            example:
              itemId: 10044
              ammount: 1          
        responses:
          200:
            description: The item was removed successfully
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
    /inventory/cosmetics:
      get:
        description: Request an user's currently equipped cosmetics.          
        responses:
          200:
            description: The user's currently equipped cosmetics.
            body:
              application/json:
                type: UserCosmetics
                example:
                  ctItem: 1033
                  terItem: 1034
                  headItem: 10062
                  gloveItem: 30018
                  backItem: 20042
                  stepsItem: 40016
                  cardItem: 60001
                  sprayItem: 42003
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
      post:
        description: Set an user's equipped cosmetics
        body:
          application/json:   
            type: UserCosmetics
            description: The new cosmetics to equip in an user's inventory.
            example:
              ctItem: 1033
              terItem: 1034
              headItem: 10062
              gloveItem: 30018
              backItem: 20042
              stepsItem: 40016
              cardItem: 60001
              sprayItem: 42003             
        responses:
          200:
            description: The cosmetics were set sucessfully.
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
    /inventory/loadout:
      get:
        description: Request an user's loadout.
        body:
          application/json:   
            properties:
              loadoutNum:
                type: integer
                description: The requested user's loadout number
                example: 0
        responses:
          200:
            description: The user's loadout details.
            body:
              application/json:
                type: UserLoadout
                example:
                  loadoutNum: 0
                  primary: 5218
                  secondary: 5288
                  melee: 84
                  hegrenade: 4
                  flash: 23
                  smoke: 8
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
      post:
        description: Set an user's loadout
        body:
          application/json:   
            type: UserLoadout
            description: The new loadout to set in an user's inventory.
            example:
              loadoutNum: 0
              primary: 5218
              secondary: 5288
              melee: 84
              hegrenade: 4
              flash: 23
              smoke: 8       
        responses:
          200:
            description: The cosmetics were set sucessfully.
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
    /inventory/buymenu:
      get:
        description: Request an user's buy menu.
        responses:
          200:
            description: The user's current buy menu.
            body:
              application/json:
                type: UserBuyMenu
                description: The current buy menu data.
                example:
                  pistols: 
                    index: 0
                    weapons:
                      - 5271
                      - 5245
                      - 5358
                      - 5288
                      - 106
                      - 5119
                      - 5121
                      - 5360
                      - 5294
                  shotguns: 
                    index: 1
                    weapons:
                      - 5130
                      - 5181
                      - 5157
                      - 5282
                      - 5286
                      - 5343
                      - 5264
                      - 5265
                      - 5230
                  smgs: 
                    index: 2
                    weapons:
                      - 5251
                      - 5295
                      - 162
                      - 5132
                      - 5346
                      - 5320
                      - 5287
                      - 5321
                      - 5310
                  rifles: 
                    index: 3
                    weapons:
                      - 5136
                      - 5142
                      - 45
                      - 46
                      - 5218
                      - 5240
                      - 5259
                      - 5309
                      - 5370
                  snipers: 
                    index: 4
                    weapons:
                      - 5133
                      - 5118
                      - 5216
                      - 86
                      - 5338
                      - 5241
                      - 5225
                      - 5369
                      - 5244
                  machineguns: 
                    index: 5
                    weapons:
                      - 5125
                      - 5289
                      - 5226
                      - 5332
                      - 5352
                      - 5363
                      - 5311
                      - 5260
                      - 5234
                  melees: 
                    index: 6
                    weapons:
                      - 5353
                      - 5362
                      - 5330
                      - 5303
                      - 5304
                      - 5305
                      - 5365
                      - 5231
                      - 5232
                  equipment: 
                    index: 7
                    weapons:
                      - 36
                      - 37
                      - 23
                      - 4
                      - 7
                      - 34
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
      post:
        description: Set an user's buy sub menu
        body:
          application/json:   
            type: UserBuySubMenu
            description: The buy menu to set in an user's inventory.
            example:   
              index: 2  
              weapons: 
                - 5251
                - 5295
                - 162
                - 5132
                - 5346
                - 5320
                - 5287
                - 5321
                - 5310  
        responses:
          200:
            description: The sub menu was set sucessfully.
          400:
            description: The request is malformed.
          404:
            description: The user does not exist.
  /signup:
    post:
      description: Request to create a new user
      body:
        application/json:   
          type: SignupRequest
          description: The new user's signup details.
          example:
            username: "gamer"  
            playername: "VeryGoodGamer"            
            password: "123456"              
      responses:
        201:
          description: The user was created sucessfully.
        400:
          description: The request is malformed.
        409:
          description: The user name or player name are unavailable.
  /login:
    put:
      description: Request to login an user
      body:
        application/json:   
          type: LoginRequest
          description: The user's login details.
          example:
            username: "gamer"              
            password: "123456"              
      responses:
        200:
          description: The user was logged in sucessfully.
          body:
            application/json:
              type: BaseUser
              example: 
                userId: 123
                username: "gamer"
                playername: "VeryGoodGamer"
        400:
          description: The request is malformed.
        401:
          description: The user's credentials are wrong.
  /logout:
    put:
      description: Request to logout an user
      body:
        application/json:   
          properties: 
            userId:
              type: integer
              example: 123
              description: The user's ID number              
      responses:
        200:
          description: The user was logged out sucessfully.
        400:
          description: The request is malformed.
        404:
          description: The user does not exist.
